### PR TITLE
fix: docs for source account

### LINKED ISSUE #532: soroban-cli: help output should include usage of 'source' subcommand parameter
### What version are you using?

latest build from main branch, as of 3/23, it was `a11c0371a974dc06845b1fde485ec681fe3f9e7d`

### What did you do?

`soroban contract deploy -h` or `soroban contract invoke -h`

### What did you expect to see?
the cli help console output in this context would include a section for describing how to use the `source` parameter, what values can it accept? a strkey encoded secret key, identity config name, others?

### What did you see instead?
no cli help console output on `source` parameter

### PR DESCRIPTION
**Pull request by willemneal**
### What

Fixes #532 

### Why

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

### CODE REVIEW

File: cmd/soroban-cli/src/commands/config/mod.rs [hunk 1]
```diff
@@ -63,15 +63,32 @@ pub struct Args {
...
 
     #[arg(long, alias = "source", env = "SOROBAN_ACCOUNT")]
-    /// Account that signs the final transaction.
-    /// S...          a seceret key
-    /// alice         an identity
-    /// 'kite urban.  a seed phrase
-    /// DEFAULT       Is the key generated with `identity generate --seed 0000000000000000
+    /// Account that signs the final transaction. Alias `source`
+    ///
+    /// SC36BWNUOCZA...  a seceret key
```
Comment (paulbellamy) [inline cmd/soroban-cli/src/commands/config/mod.rs:68]:
```suggestion
    /// SC36BWNUOCZA...  a secret key
```

**Review by paulbellamy — APPROVED** [review]
Couple typos, but lgtm.

File: cmd/soroban-cli/src/commands/config/mod.rs (hunk 1 above)
Comment (willemneal) [reply cmd/soroban-cli/src/commands/config/mod.rs:68]: This one always gets me.

File: docs/soroban-cli-full-docs.md [hunk 2]
```diff
@@ -160,7 +160,7 @@ Install a WASM file to the ledger without creating a contract instance
 * `--network-passphrase <NETWORK_PASSPHRASE>` — Network passphrase to sign the transaction sent to the rpc server
 * `--network <NETWORK>` — Name of network to use from config
 * `--ledger-file <LEDGER_FILE>` — File to persist ledger state, default is `.soroban/ledger.json`
-* `--source-account <SOURCE_ACCOUNT>` — Account that signs the final transaction. S...          a seceret key alice         an identity 'kite urban.  a seed phrase DEFAULT       Is the key generated with `identity generate --seed 0000000000000000
+* `--source-account <SOURCE_ACCOUNT>` — Account that signs the final transaction. Alias `source`
```
Comment (chadoh) [inline docs/soroban-cli-full-docs.md:163]: Since the multi-line comments don't show up here, should we consider adding this extra info to the long help for `invoke` itself?

File: cmd/soroban-cli/src/commands/config/mod.rs [hunk 3]
```diff
@@ -63,15 +63,32 @@ pub struct Args {
...
+    ///
+    ///     --source SC36BWNUOCZAO7DMEJNNKFV6BOTPJP7IG5PSHLUOLT6DZFRU3D3XGIXW
     pub source_account: Option<String>,
 
     #[arg(long)]
     /// If using a seed phrase, which hd path to use, e.g. `m/44'/148'/{hd_path}`
+    ///
+    /// Example: `--hd-path 1`
+    ///
+    /// Default is `0`
```
Comment (chadoh) [inline cmd/soroban-cli/src/commands/config/mod.rs:91]: If we like the idea of making these single (long) lines, we could replace this with:

```suggestion
    /// If using a seed phrase, which hierarchical deterministic path to use, e.g. `m/44'/148'/{hd_path}`. Example: `--hd-path 1`. Default: `0`
```

Another question: is that `e.g.` value accurate? Seems like it's missing a couple segments, based on others I've seen and the examples in [this article](https://medium.com/myetherwallet/hd-wallets-and-derivation-paths-explained-865a643c7bf2).

File: docs/soroban-cli-full-docs.md (hunk 2 above)
Comment (willemneal) [reply docs/soroban-cli-full-docs.md:163]: If we could fork the markdown generator we fix the multiline issue that way.  But save it for a future PR.

File: cmd/soroban-cli/src/commands/config/mod.rs [hunk 4]
```diff
@@ -63,15 +63,28 @@ pub struct Args {
...
+    /// If not provided the default is the seed phrase generated by  
+    /// `identity generate --default-seed`
+    ///
+    /// Examples:
+    ///
+    ///     --source alice
+    ///
+    ///     --source "kite urban.."
+    ///
+    ///     --source SC36BWNUOCZAO7DMEJNNKFV6BOTPJP7IG5PSHLUOLT6DZFRU3D3XGIXW
```
Comment (chadoh) [inline cmd/soroban-cli/src/commands/config/mod.rs:83]: Since multiline argument comments are not well supported in any context, how about this:

```suggestion
    /// Account that signs the final transaction. Alias `source`. Can be an identity (--source alice), a secret key (--source SC36…), or a seed phrase (--source "kite urban…"). Default: `identity generate --default-seed`
```
